Theme update and index page styling
eclipse-cyclonedds/eclipse-cyclonedds.github.io pull request #2
Opened 2021-05-28 12:36 UTC by thijsmie

2021-05-28 12:43 UTC, k0ekk0ek requested changes
Thanks @thijsmie! Mostly LGTM, just the name thingy and I'll be happy to merge :+1:

2021-05-28 12:43 UTC, k0ekk0ek commented on pelicanconf.py
> +            ('ADLINK Technology', 'https://www.adlinktech.com', 'images/company_logo.svg'),)
Better name this `adlink.svg` since other companies might start contributing as well. e.g. APEX.AI might want it's logo here.

2021-05-31 07:55 UTC, k0ekk0ek requested changes

2021-05-31 07:55 UTC, k0ekk0ek commented on pelicanconf.py
> +    'page_with_slug_index': page_with_slug_index,
We can probably remove the `page_with_slug_index` entirely if we have a more generic one(?)

2021-05-31 07:56 UTC, k0ekk0ek commented
I think I like the poetry thing as well, perhaps we should make that mandatory? And is there a nice pythonic way of downloading the resources?

2021-05-31 09:37 UTC, thijsmie commented
Making poetry mandatory is 'hard' in the sense that it is just a package managing tool and there is nothing stopping people from just running `pip install pelican`. However, I do think it is a good idea to recommend in the Readme to use `poetry install` instead.

2021-05-31 11:19 UTC, k0ekk0ek commented
Looks great @thijsmie, thanks!

2021-05-31 11:19 UTC, merged