main page content provision
eclipse-cyclonedds/eclipse-cyclonedds.github.io pull request #4
Opened 2021-06-08 12:49 UTC by RamziKaroui

Signed-off-by: Ramzi KAROUI <ramzi.karoui@adlinktech.com>

main page content creation

2021-06-11 08:29 UTC, k0ekk0ek requested changes

2021-06-11 08:29 UTC, k0ekk0ek commented on content/pages/index.rst
> +Cyclone also has a low footprint making it suitable for both enterprise and embedded systems.​
Please use *Cyclone DDS* consistently. I know everybody knows we mean Cyclone DDS when we say Cyclone but still. The official name is Cyclone DDS. (Should of course have been *Splice*, but still).

2021-06-11 08:29 UTC, k0ekk0ek commented on content/pages/index.rst
> +Cyclone DDS is a high performing, OMG-DDS standard based data sharing technology which allows system designers to create digital twines of their systems’ entities to share their states, events, data-
twines >> twins

2021-06-11 08:30 UTC, k0ekk0ek commented
Thanks @RamziKaroui! Thanks for providing some content :+1: Couple of minor things, other than that, this seems absolutely fine.

2021-06-11 08:49 UTC, thijsmie commented
I have a couple of comments on the css styling here: the original content was carefully constructed to get the `container > row > col-*` structure. This is not quite right in this commit, meaning you will see a horizontal scrollbar appear because the content is not correctly fixed-width to the viewport.
Next, the change of the `col-6 col-md-2 pb-2` to `col-md-2` messes with the responsive setup of the website. The point of these  is that the first class `col-*` select the rendering from the smallest viewports and then the `col-md-*` variants from medium viewports and up, as explained [here](https://getbootstrap.com/docs/5.0/layout/grid/). I recommend you view the site with the [chrome mobile device simulator](https://developer.chrome.com/docs/devtools/device-mode/) in a bunch of sizings to get a feel for this.

2021-06-15 07:13 UTC, k0ekk0ek commented
@thijsmie, it looks decent if I run it in the responsive mode in Firefox. Is the css ok now or do we still require changes?

2021-06-15 07:21 UTC, thijsmie commented
My requested changes were made so the CSS is okay now.

2021-06-15 08:59 UTC, merged